["raid"] = {
["debuffBorderColorBleed"] = {
["r"] = 1,
["g"] = 0,
["b"] = 0,
},
["absorbBarOvershieldAlpha"] = 0.8,
["targetedSpellHighlightColor"] = {
["r"] = 1,
["g"] = 0.8,
["b"] = 0,
},
["fadeDeadIcons"] = 1,
["debuffPaddingY"] = 2,
["dispelIconSize"] = 20,
["debuffBorderColorDisease"] = {
["r"] = 0.6,
["g"] = 0.4,
["b"] = 0,
},
["hideBlizzardRaidFrames"] = true,
["personalTargetedSpellDurationY"] = 0,
["aggroHighlightMode"] = "SOLID",
["healPredictionAnchor"] = "CENTER",
["nameTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["missingBuffIconSize"] = 24,
["raidGroupSpacing"] = 0,
["personalTargetedSpellDurationFont"] = "Fonts\\FRIZQT__.TTF",
["raidTargetIconFrameLevel"] = 0,
["testShowIcons"] = true,
["defensiveIconX"] = 0,
["healPredictionClampMode"] = 1,
["testDebuffCount"] = 2,
["debuffDurationX"] = 0,
["raidTargetIconHide"] = false,
["buffExpiringThreshold"] = 30,
["buffStackY"] = 0,
["buffCountdownOutline"] = "OUTLINE",
["healthTextAbbreviate"] = true,
["tooltipFrameAnchor"] = "DEFAULT",
["personalTargetedSpellShowSwipe"] = true,
["dispelAnimate"] = false,
["tooltipDebuffAnchor"] = "FRAME",
["defensiveIconEnabled"] = true,
["petShowHealthText"] = false,
["absorbBarOvershieldReverse"] = false,
["buffShowDuration"] = true,
["centerStatusIconAnchor"] = "CENTER",
["tooltipAuraDisableInCombat"] = false,
["testShowAggro"] = false,
["targetedSpellDurationScale"] = 1,
["dispelShowGradient"] = true,
["buffAlpha"] = 1,
["selectionHighlightInset"] = 2,
["buffExpiringBorderColorByTime"] = false,
["buffFilterPlayer"] = true,
["restedIndicatorAnchor"] = "TOPRIGHT",
["dispelIconAlpha"] = 1,
["backgroundColorMode"] = "CUSTOM",
["dispelGradientBlendMode"] = "BLEND",
["buffOffsetY"] = 0,
["hideBlizzardFrames"] = true,
["dispelIconOffsetY"] = 0,
["healthTextOutline"] = "OUTLINE",
["petGroupOffsetX"] = 5,
["healthFontSize"] = 15,
["statusTextFont"] = "기본 글꼴",
["debuffStackY"] = 0,
["dispelDiseaseColor"] = {
["r"] = 0.6,
["g"] = 0.4,
["b"] = 0,
},
["targetedSpellShowInterrupted"] = true,
["petGroupShowLabel"] = true,
["targetedSpellNameplateOffscreen"] = false,
["oorHealthTextAlpha"] = 0.25,
["readyCheckIconScale"] = 1.6000000238419,
["sortRoleOrder"] = {
"TANK",
"HEALER",
"MELEE",
"RANGED",
},
["targetedSpellAnchor"] = "LEFT",
["nameTextY"] = 7,
["healthColor"] = {
["a"] = 1,
["r"] = 0.1019607931375504,
["g"] = 0.1019607931375504,
["b"] = 0.1019607931375504,
},
["bossDebuffsBorderScale"] = 1,
["petGroupAnchor"] = "RIGHT",
["roleIconShowHealer"] = true,
["targetedSpellInterruptedXColor"] = {
["r"] = 1,
["g"] = 0,
["b"] = 0,
},
["statusTextAnchor"] = "CENTER",
["missingBuffIconShowBorder"] = true,
["classColorAlpha"] = 1,
["nameTextTruncateMode"] = "ELLIPSIS",
["anchorX"] = 0,
["petHealthColor"] = {
["b"] = 0,
["g"] = 0.8,
["r"] = 0,
},
["buffWrap"] = 3,
["targetedSpellInterruptedDuration"] = 0.5,
["debuffClickThroughKeybinds"] = true,
["selectionHighlightColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["resourceBarBackgroundEnabled"] = true,
["fadeDeadName"] = 1,
["fadeDeadBackgroundColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0.3019607961177826,
},
["bossDebuffsOffsetY"] = 7,
["defensiveIconSize"] = 25,
["roleIconHide"] = false,
["targetedSpellHighlightSize"] = 3,
["showFrameBorder"] = true,
["targetedSpellInBattlegrounds"] = true,
["deadHealthTextAlpha"] = 0.3,
["tooltipBuffX"] = 0,
["healPredictionFrameLevel"] = 12,
["buffDurationFont"] = "GothamNarrowUltra",
["testShowPets"] = true,
["debuffWrapOffsetX"] = 0,
["buffStackOutline"] = "OUTLINE",
["defensiveBarEnabled"] = true,
["debuffWrap"] = 3,
["debuffDurationColorByTime"] = false,
["deadBackgroundAlpha"] = 0.3,
["targetedSpellSortNewestFirst"] = true,
["raidPlayerAnchor"] = "START",
["buffMax"] = 5,
["sortEnabled"] = true,
["fadeDeadUseCustomColor"] = true,
["defensiveIconDurationOutline"] = "OUTLINE",
["backgroundClassAlpha"] = 1,
["healPredictionOverflowPercent"] = 0,
["personalTargetedSpellInterruptedTintAlpha"] = 0.5,
["leaderIconAnchor"] = "LEFT",
["bossDebuffsSpacing"] = 2,
["roleIconScale"] = 1,
["raidEnabled"] = true,
["tooltipBuffAnchor"] = "FRAME",
["buffDurationScale"] = 1.5,
["personalTargetedSpellInRaids"] = true,
["missingBuffIconBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 1,
},
["testShowMissingBuff"] = false,
["deadNameAlpha"] = 0.5,
["oorDispelOverlayAlpha"] = 0.20000000298023,
["defensiveIconScale"] = 1.5,
["debuffFilterMode"] = "BLIZZARD",
["missingBuffIconBorderSize"] = 2,
["sortSeparateMeleeRanged"] = false,
["buffExpiringTintColor"] = {
["a"] = 0.46354159712791,
["r"] = 1,
["g"] = 0,
["b"] = 0.12156863510609,
},
["buffCountdownY"] = 0,
["hidePlayerFrame"] = false,
["readyCheckIconHide"] = false,
["tooltipFrameY"] = 0,
["absorbBarX"] = 0,
["oorPowerBarAlpha"] = 0.20000000298023,
["healAbsorbBarWidth"] = 50,
["healPredictionReverse"] = false,
["statusTextY"] = 0,
["dispelShowBorder"] = true,
["absorbBarMode"] = "OVERLAY",
["debuffStackOutline"] = "OUTLINE",
["personalTargetedSpellShowBorder"] = true,
["raidTargetIconScale"] = 1.1000000238419,
["buffExpiringBorderInset"] = 1,
["defensiveBarX"] = 0,
["targetedSpellHighlightInset"] = 2,
["targetedSpellHighlightImportant"] = true,
["selectionHighlightAlpha"] = 1,
["testShowExternalDef"] = false,
["absorbBarFrameLevel"] = 11,
["healPredictionOthersColor"] = {
["a"] = 0.7,
["r"] = 0,
["g"] = 0.5,
["b"] = 0.8,
},
["raidFlatPlayerAnchor"] = "START",
["masqueBorderControl"] = false,
["missingBuffCheckVersatility"] = true,
["buffDurationColorByTime"] = true,
["debuffShowCountdown"] = false,
["targetedSpellDurationColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["oorDefensiveIconAlpha"] = 0.5,
["resourceBarX"] = 0,
["readyCheckIconEnabled"] = true,
["healAbsorbBarX"] = 0,
["externalDefEnabled"] = true,
["personalTargetedSpellDurationColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["groupLabelOffsetY"] = 5,
["bossDebuffsScaleText"] = true,
["debuffStackMinimum"] = 2,
["debuffDurationY"] = 0,
["debuffOffsetY"] = 2,
["healthTextY"] = 0,
["personalTargetedSpellX"] = 0,
["personalTargetedSpellInArena"] = true,
["buffCountdownX"] = 0,
["absorbBarShowOvershield"] = false,
["dispelGradientStyle"] = "TOP",
["personalTargetedSpellInterruptedDuration"] = 0.5,
["targetedSpellMaxIcons"] = 5,
["testAnimateHealth"] = true,
["externalDefBorderSize"] = 2,
["defensiveBarShowDuration"] = true,
["petBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["roleIconShowTank"] = true,
["aggroHighlightAlpha"] = 1,
["petHealthAnchor"] = "RIGHT",
["externalDefY"] = 0,
["dispelOverlayMode"] = "PLAYER_DISPELLABLE",
["hideBlizzardPartyFrames"] = false,
["buffExpiringTintEnabled"] = false,
["healthColorMedium"] = {
["a"] = 1,
["r"] = 0.760784387588501,
["g"] = 0.760784387588501,
["b"] = 0.207843154668808,
},
["dispelGradientSize"] = 0.5,
["roleIconHideHealer"] = false,
["raidGroupOrder"] = "NORMAL",
["petNameMaxLength"] = 8,
["healPredictionShowMode"] = "MINE",
["testShowStatusIcons"] = true,
["healAbsorbBarBackgroundColor"] = {
["a"] = 0.4570315182209,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["raidAnchorX"] = 1.66668701171875,
["debuffExpiringBorderPulsate"] = true,
["leaderIconFrameLevel"] = 0,
["dispelBorderInset"] = 0,
["petShowBorder"] = true,
["absorbBarReverse"] = false,
["externalDefScale"] = 1.5,
["defensiveIconDurationFont"] = "GothamNarrowUltra",
["nameFontSize"] = 14,
["missingHealthColorMode"] = "CUSTOM",
["debuffHideSwipe"] = false,
["petTexture"] = "Interface\\TargetingFrame\\UI-StatusBar",
["defensiveIconFrameLevel"] = 0,
["resourceBarHealerOnly"] = true,
["sortClassOrder"] = {
"DEATHKNIGHT",
"DEMONHUNTER",
"DRUID",
"EVOKER",
"HUNTER",
"MAGE",
"MONK",
"PALADIN",
"PRIEST",
"ROGUE",
"SHAMAN",
"WARLOCK",
"WARRIOR",
},
["deadBackgroundColor"] = {
["a"] = 1,
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["healthColorLowWeight"] = 1,
["tooltipDebuffDisableInCombat"] = false,
["dispelCurseColor"] = {
["r"] = 0.6,
["g"] = 0,
["b"] = 1,
},
["targetedSpellInDungeons"] = true,
["statusTextEnabled"] = true,
["personalTargetedSpellInterruptedShowX"] = true,
["buffDurationY"] = -8,
["missingHealthColor"] = {
["a"] = 0.8,
["b"] = 0,
["g"] = 0,
["r"] = 0.5,
},
["groupLabelFontSize"] = 12,
["statusTextOutline"] = "OUTLINE",
["targetedSpellGrowth"] = "DOWN",
