local DUI = unpack(DDingUI_Profile)
local LSM = LibStub("LibSharedMedia-3.0")

local mediaPath = "Interface\\AddOns\\DDingUI_Profile\\Media\\"

-- 모든 로케일에서 폰트가 보이도록 마스크 설정
local allLocales = LSM.LOCALE_BIT_koKR + LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_zhCN + LSM.LOCALE_BIT_zhTW + LSM.LOCALE_BIT_western

------------------------------------------------------------------------
-- 폰트 (4)
------------------------------------------------------------------------
LSM:Register("font", "DDing Asia",               mediaPath .. "Fonts\\DDingAsia.ttf", allLocales)
LSM:Register("font", "Gotham Narrow Ultra Asia",  mediaPath .. "Fonts\\GothamNarrowUltraAsia.ttf", allLocales)
LSM:Register("font", "Noto Sans JP Black",        mediaPath .. "Fonts\\NotoSansJP-Black.ttf", allLocales)
LSM:Register("font", "SAO Welcome Bold",          mediaPath .. "Fonts\\SAOWelcomeTT-Bold.ttf", allLocales)

------------------------------------------------------------------------
-- 텍스처 (1)
------------------------------------------------------------------------
LSM:Register("statusbar", "DDing Melli",           mediaPath .. "Textures\\Melli.tga")
LSM:Register("statusbar", "DDing BuiOnePixel",     mediaPath .. "Textures\\BuiOnePixel.tga")

------------------------------------------------------------------------
-- 사운드 (47)
------------------------------------------------------------------------
LSM:Register("sound", "DD Aggro",                  mediaPath .. "Sounds\\aggro.ogg")
LSM:Register("sound", "DD Air Horn",               mediaPath .. "Sounds\\AirHorn.ogg")
LSM:Register("sound", "DD Arrow Swoosh",           mediaPath .. "Sounds\\Arrow_Swoosh.ogg")
LSM:Register("sound", "DD Bam",                    mediaPath .. "Sounds\\bam.ogg")
LSM:Register("sound", "DD Bear Polar",             mediaPath .. "Sounds\\bear_polar.ogg")
LSM:Register("sound", "DD Big Kiss",               mediaPath .. "Sounds\\bigkiss.ogg")
LSM:Register("sound", "DD Bite",                   mediaPath .. "Sounds\\BITE.ogg")
LSM:Register("sound", "DD Burp",                   mediaPath .. "Sounds\\burp4.ogg")
LSM:Register("sound", "DD Cat",                    mediaPath .. "Sounds\\cat2.ogg")
LSM:Register("sound", "DD Chant 2",                mediaPath .. "Sounds\\chant2.ogg")
LSM:Register("sound", "DD Chant 4",                mediaPath .. "Sounds\\chant4.ogg")
LSM:Register("sound", "DD Chimes",                 mediaPath .. "Sounds\\chimes.ogg")
LSM:Register("sound", "DD Cookie",                 mediaPath .. "Sounds\\cookie.ogg")
LSM:Register("sound", "DD Alert 44",               mediaPath .. "Sounds\\DD_Alert-44.ogg")
LSM:Register("sound", "DD Alert Kick Punch",       mediaPath .. "Sounds\\DD_Alert-kick-punch.ogg")
LSM:Register("sound", "DD Ancestral Win",          mediaPath .. "Sounds\\DD_Ancestral Win.ogg")
LSM:Register("sound", "DD Award Win",              mediaPath .. "Sounds\\DD_Award Win.ogg")
LSM:Register("sound", "DD Bloodlust",              mediaPath .. "Sounds\\DD_bloodlust.ogg")
LSM:Register("sound", "DD Celestial Win",          mediaPath .. "Sounds\\DD_Celestial Win.ogg")
LSM:Register("sound", "DD Ding Alert",             mediaPath .. "Sounds\\DD_Ding-Sound-Effect-Alert.ogg")
LSM:Register("sound", "DD Music Accent",           mediaPath .. "Sounds\\DD_MusicAccent EC09_07_1.ogg")
LSM:Register("sound", "DD SAO Death Tone",         mediaPath .. "Sounds\\DD_sao_death_tone.ogg")
LSM:Register("sound", "DD SAO Message",            mediaPath .. "Sounds\\DD_sao_message_sound.ogg")
LSM:Register("sound", "DD SAO Death Tone 2",       mediaPath .. "Sounds\\DD_SAO-death-tone.ogg")
LSM:Register("sound", "DD Small Win",              mediaPath .. "Sounds\\DD_Small Win.ogg")
LSM:Register("sound", "DD Starburst Stream",       mediaPath .. "Sounds\\DD_Starburst-Stream.ogg")
LSM:Register("sound", "DD Success",                mediaPath .. "Sounds\\DD_success-notification.ogg")
LSM:Register("sound", "DD Super Retro Win",        mediaPath .. "Sounds\\DD_Super Retro Win.ogg")
LSM:Register("sound", "DD Wake Up",                mediaPath .. "Sounds\\DD_wake_up.ogg")
LSM:Register("sound", "DD Win Fanfare",            mediaPath .. "Sounds\\DD_Win Fanfare.ogg")
LSM:Register("sound", "DD Win Pop Up",             mediaPath .. "Sounds\\DD_Win Pop Up.ogg")
LSM:Register("sound", "DD Win Sound",              mediaPath .. "Sounds\\DD_Win Sound.ogg")
LSM:Register("sound", "DD Electric Spark",         mediaPath .. "Sounds\\ESPARK1.ogg")
LSM:Register("sound", "DD Fireball",               mediaPath .. "Sounds\\Fireball.ogg")
LSM:Register("sound", "DD Gasp",                   mediaPath .. "Sounds\\Gasp.ogg")
LSM:Register("sound", "DD Heartbeat",              mediaPath .. "Sounds\\heartbeat.ogg")
LSM:Register("sound", "DD Hiccup",                 mediaPath .. "Sounds\\hic3.ogg")
LSM:Register("sound", "DD Huh",                    mediaPath .. "Sounds\\huh_1.ogg")
LSM:Register("sound", "DD Hurricane",              mediaPath .. "Sounds\\hurricane.ogg")
LSM:Register("sound", "DD Hyena",                  mediaPath .. "Sounds\\hyena.ogg")
LSM:Register("sound", "DD Kaching",                mediaPath .. "Sounds\\kaching.ogg")
LSM:Register("sound", "DD Moan",                   mediaPath .. "Sounds\\moan.ogg")
LSM:Register("sound", "DD Panther",                mediaPath .. "Sounds\\panther1.ogg")
LSM:Register("sound", "DD Phone",                  mediaPath .. "Sounds\\phone.ogg")
LSM:Register("sound", "DD Punch",                  mediaPath .. "Sounds\\PUNCH.ogg")
LSM:Register("sound", "DD Rain Roof",              mediaPath .. "Sounds\\rainroof.ogg")
LSM:Register("sound", "DD Rocket",                 mediaPath .. "Sounds\\rocket.ogg")
LSM:Register("sound", "DD Ship Whistle",           mediaPath .. "Sounds\\shipswhistle.ogg")
LSM:Register("sound", "DD Shot",                   mediaPath .. "Sounds\\shot.ogg")
LSM:Register("sound", "DD Snake Attack",           mediaPath .. "Sounds\\snakeatt.ogg")
LSM:Register("sound", "DD Sneeze",                 mediaPath .. "Sounds\\sneeze.ogg")
LSM:Register("sound", "DD Sonar",                  mediaPath .. "Sounds\\sonar.ogg")
LSM:Register("sound", "DD Splash",                 mediaPath .. "Sounds\\splash.ogg")
LSM:Register("sound", "DD Squeaky Pig",            mediaPath .. "Sounds\\Squeakypig.ogg")
LSM:Register("sound", "DD Sword Echo",             mediaPath .. "Sounds\\swordecho.ogg")
LSM:Register("sound", "DD Throw Knife",            mediaPath .. "Sounds\\throwknife.ogg")
LSM:Register("sound", "DD Thunder",                mediaPath .. "Sounds\\thunder.ogg")
LSM:Register("sound", "DD Water Drop",             mediaPath .. "Sounds\\WaterDrop.ogg")
LSM:Register("sound", "DD Wicked Laugh",           mediaPath .. "Sounds\\wickedmalelaugh1.ogg")
LSM:Register("sound", "DD Wilhelm",                mediaPath .. "Sounds\\wilhelm.ogg")
LSM:Register("sound", "DD Woman Laugh",            mediaPath .. "Sounds\\wlaugh.ogg")
LSM:Register("sound", "DD Wolf",                   mediaPath .. "Sounds\\wolf5.ogg")
LSM:Register("sound", "DD Xylophone",              mediaPath .. "Sounds\\Xylophone.ogg")
LSM:Register("sound", "DD Yeehaw",                 mediaPath .. "Sounds\\yeehaw.ogg")
